### ISSUE TITLE
引用样式好像没有生效？

### ISSUE THREAD

**Issue by weijiang1994** [greyli/flask-ckeditor#43]
运行示例程序中，发现引用块提交后样式会变成普通p标签的样式，不知道是不是CKEditor的bug。

**Comment by weijiang1994** [comment]
可能是CKEditor的样式没有生效，我在显示页面重写了`blockquote`的样式，我用的代码样式如下所示:
```css
blockquote {
            font: 14px/22px normal helvetica, sans-serif;
            margin-top: 10px;
            margin-bottom: 10px;
            margin-left: 0px;
            padding: 10px 10px 10px 15px;
            border-left: 3px solid #70b8f0;
            background-color:rgba(0,132,255,.08);
            border-radius: 0px 8px 8px 0px ;
        }
```
由于*CKEditor*中的`p`标签默认带有`margin-bottom:16px`属性，在`blockquote`中看起来很别扭，不居中，因此还加了个子元素`p`标签的样式，代码如下：
```css
blockquote>p {
            font: 14px/22px normal helvetica, sans-serif;
            margin: 5px 0px 5px 0px;
            font-style:italic;
        }
```
